#!/usr/bin/env ruby

infile = File.open('data/characters.txt')

num = 5
headers = %w[survival award recovery learn]
printf("%-15s", "Person")
headers.each {|h|
  printf("%-10s " % h.capitalize)
}
puts

infile.each_line {|line|
  line = line.strip()
  if line.length > 1
    printf("%-15s " % line)
    headers.length.times {
      roll = rand(1..6) + rand(1..6)
      printf("%-10d " % roll)
    }
    puts
  end
}
